version: "3.9"

services:
  wildfire-mock:
    build: .
    working_dir: /app
    command:
      [
        "python3",
        "-m",
        "src.main",
        "--input",
        "wildfire_24fps.mp4",
        "--output",
        "experiments/results/docker_mock",
        "--profile",
        "--frame-stride",
        "30",
        "--detector",
        "yolo",
        "--yolo-model",
        "yolov8n",
        "--yolo-backend",
        "mock",
        "--environment-name",
        "docker_mock",
        "--run-type",
        "single_process_docker_mock"
      ]
    volumes:
      - ./:/app
